version: "2"

volumes:
    db-data:
        external: false

services:
    db:
        image: mongo
        env_file: .env
        volumes:
            - db-data:/data/db

    app:
        build: .
        env_file: .env
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
        depends_on:
            - db